apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx
  labels:
    tier: nginx
spec:
  # modify replicas according to your case
  replicas: 2
  selector:
    matchLabels:
      tier: nginx
  template:
    metadata:
      labels:
        tier: nginx #spec for replicaset
    spec:
      containers:
        - name: nginx
          image: nginx #spec for container nginx