---
apiversion: v1
kind: ConfigMap
metadata: #name of the configmap
  name: sample3
data:
  URL: tradeview.com
  COURSE: DEVOPS
  TYPE: onlineclass

---
apiversion: v1
kind: pod
metadata:
  name: sample3
spec:
  containers:
    - name: centos
      image: centos:7
      command: ["sleep","20"]
      envfrom:
        - configMapRef:
            name: sample


