---
apiVersion: v1
kind: Secret
metadata: #name of the secret
  name: sample
data:
  URL: "dHJhZGluZ3ZpZXcuY29tCg==" #echo tradingview.com |base64

---
apiVersion: v1
kind: Pod
metadata:
  name: secret
spec:
  containers:
    - name: centos
      image: centos:7
      command: ["sleep","10"]
      envFrom:
        - secretRef:
            name: sample